### ISSUE TITLE
Hyde is apparently abandoned

### ISSUE THREAD

**Issue by elucify** [hyde/hyde.github.com#10]
Please take this repo down if you're not going to maintain it. It wastes peoples' time.

**Comment by lakshmivyas** [comment]
@elucify -  Have you seen the commits on the [hyde](http://github.com/hyde/hyde) repo?

I don't think you should speak for "The people".   If your time has been wasted, I'd like to apologize.  However,  I don't understand how the existence of a repository can be a waste of time for someone.

Lot of the open source work is done out of personal cost - please be nice.
