### ISSUE TITLE
"Pain points" link on home page leads to a 404

### ISSUE THREAD

**Issue by ghost** [hyde/hyde.github.com#11]
Hilariously, clicking the "pain points" link on the home page leads to a 404.

**Comment by jonafato** [comment]
Thanks for reporting this issue! There are a few possibilities here:
- Hyde has successfully removed the pain points of creating and maintaining static websites.
- This 404 is itself is an example of a pain point, and you've stumbled upon a clever joke.
- The link is broken, and the documentation can use improvement. (This is almost certainly the case.)

As of hyde/hyde#314, I've begun moving the documentation from its current locations to a Sphinx-based solution hosted at [Read the Docs](https://hyde.readthedocs.io/en/latest/). The site hosted at hyde.github.io is planned to change from what it is to a higher level informational site about the project with the full documentation living at the new RTD site. This is a work in progress, and contributions toward better documentation and guides / tutorials are much appreciated. If you'd like to help out, please open an [issue](/hyde/hyde/issues) or a [pull request](/hyde/hyde/pulls).
