### ISSUE TITLE
pip installation problems (typogrify-hyde missing from PyPI?)

### ISSUE THREAD

**Issue by jhamon** [hyde/hyde.github.com#5]
When I run `pip install hyde` I run into the following problem:

    Downloading/unpacking typogrify-hyde (from hyde)
      Could not find any downloads that satisfy the requirement typogrify-hyde (from hyde)
    No distributions at all found for typogrify-hyde (from hyde)
    Storing complete log in /Users/jhamon/Library/Logs/pip.log`

Or the full details, from `pip install hyde --verbose`:

    Downloading/unpacking typogrify-hyde (from hyde)
      Could not fetch URL http://pypi.python.org/simple/typogrify-hyde: HTTP Error 404: Not Found (typogrify-hyde does not have any releases)
      Will skip URL http://pypi.python.org/simple/typogrify-hyde when looking for download links for typogrify-hyde (from hyde)
     Could not fetch URL http://pypi.python.org/simple/typogrify-hyde/: HTTP Error 404: Not Found (typogrify-hyde does not have any releases)
      Will skip URL http://pypi.python.org/simple/typogrify-hyde/ when looking for download links for typogrify-hyde (from hyde)
      Could not find any downloads that satisfy the requirement typogrify-hyde (from hyde)
      No distributions at all found for typogrify-hyde (from hyde)
      Exception information:
      Traceback (most recent call last):
        File "/Library/Python/2.7/site-packages/pip-1.2.1-py2.7.egg/pip/basecommand.py", line 107, in main
    status = self.run(options, args)
        File "/Library/Python/2.7/site-packages/pip-1.2.1-py2.7.egg/pip/commands/install.py", line 256, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
        File "/Library/Python/2.7/site-packages/pip-1.2.1-py2.7.egg/pip/req.py", line 1011, in prepare_files
      url = finder.find_requirement(req_to_install, upgrade=self.upgrade)
      File "/Library/Python/2.7/site-packages/pip-1.2.1-py2.7.egg/pip/index.py", line 157, in find_requirement
    raise DistributionNotFound('No distributions at all found for %s' % req)
    DistributionNotFound: No distributions at all found for typogrify-hyde (from hyde)

**Comment by jonafato** [comment]
Hyde used to use a fork of `typogrify`. This was changed in https://github.com/hyde/hyde/commit/e68eaf3880831629b39c2ef0779367c36102e65d (not long after this issue was filed). Installation should no longer cause any errors.
